# Copyright (C) 2023 tracetronic GmbH
#
# SPDX-License-Identifier: MIT

blank_issues_enabled: false
contact_links:
  - name: tracetronic Support Center
    url: https://support.tracetronic.com
    about: Please report security vulnerabilities and non-public issues (i.e. NDA relevant information) here.
