# Copyright (C) 2023 tracetronic GmbH
#
# SPDX-License-Identifier: MIT

name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install poetry
        run: pip3 install poetry
      - name: Setup Python environment
        run: poetry install --with dev
      - name: Execute Linting
        run: poetry run pylint --rcfile configPyLint.pylintrc ./UserPyModules/ --errors-only
