# Copyright (C) 2023 tracetronic GmbH
#
# SPDX-License-Identifier: MIT

name: REUSE Compliance Check

on: [push, pull_request]

jobs:
  compliance-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1
