# Copyright (C) 2023 tracetronic GmbH
#
# SPDX-License-Identifier: MIT

name: Sync labels
on:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yml
